"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Jessica North and Christiana Ozuna, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: jan3557
UT EID 2: cmo2388
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 10/21. If you choose to use
        # a dummy node, you can comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        current = self._head
        prev = None
        new_node = Node(coeff, exp)
        # if the coefficient is 0, do nothing
        if coeff == 0:
            return
        # puts the new term in the correct descending position    
        while current is not None and current.exp > exp:
            prev = current
            current = current.next
        if current is not None and current.exp == exp:
            current.coeff += coeff
            # if the summed coefficient is 0, remove the exponent
            if current.coeff == 0:
                current.exp = None
            #current.exp = current.exp.next
        else:
            current = new_node
        new_node.next = current

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        result = LinkedList()
        new_node = Node(p)
        # add new poly p to the polynomial
        self._head = new_node
        result += self._head
        return result

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        result = LinkedList()
        current_self = self._head

        while current_self is not None:
            current_p = p.head
            while current_p is not None:
                new_coeff = current_self.coeff * current_p.coeff
                new_exp = current_self.exp * current_p.exp
                result.insert_term(new_coeff, new_exp)
                current_p = current_p.next
            current_self = current_self.next
        return result
        

    # Return a string representation of the polynomial.
    def __str__(self):
        terms = []
        current = self._head

        while current is not None:
            terms.append(f"({current.coeff})({current.exp})")
            current = current.next
        terms.append("None")
        output = " -> ".join(terms)
        return output

def main():
    # read data from stdin using input() and create polynomial p
    #data = sys.stdin.read.strip().split('\n')
    p = input().split()
    # read data from stdin using input() and create polynomial q
    q = input().split()
    # get sum of p and q as a new linked list and print sum
    poly_p = LinkedList()
    for i in range(len(p)):
        coeff = int(p[i])
        exp = int(p[i + 1])
        poly_p.insert_term(coeff, exp)
    poly_q = LinkedList()
    for i in range(len(q)):
        coeff = int(q[i])
        exp = int(q[i + 1])
        poly_q.insert_term(coeff, exp)
    sum_result = poly_p.add(poly_q)
    print(f"Sum: {sum_result}")
    # get product of p and q as a new linked list and print product
    
    product_result = poly_p.mult(poly_q)
    print(f"Product: {product_result}")


if __name__ == "__main__":
    main()
